import type { DiffViewState as DiffViewState } from '../DiffViewState/DiffViewState.ts'

export const createDefaultState = (): DiffViewState => ({
  assetDir: '',
  contentLeft: '',
  contentRight: '',
  deltaY: 0,
  errorLeftMessage: '',
  errorLeftStack: '',
  errorRightMessage: '',
  errorRightStack: '',
  finalDeltaY: 0,
  focus: 0,
  gitRoot: '',
  handleOffset: 0,
  headerHeight: 40,
  height: 100,
  id: 1,
  initial: false,
  inputSource: 0,
  inputValue: '',
  isResizing: false,
  isVisible: true,
  itemHeight: 20,
<<<<<<< HEAD
  knownImageExtensions: ['.png', '.jpg', '.jpeg', '.gif', '.webp', '.avif', '.svg', '.bmp', '.ico'],
=======
  knownImageExtensions: ['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg', '.bmp', '.ico'],
  layout: 'horizontal',
>>>>>>> origin/main
  leftWidth: 48,
  lineNumbers: true,
  maxInputLines: 5,
  maxLineY: 0,
  minimumSliderSize: 30,
  minLineY: 0,
  platform: 0,
  providerId: '',
  renderModeLeft: 'text',
  renderModeRight: 'text',
  resizeOffsetX: 0,
  resizeOffsetY: 0,
  rightWidth: 48,
  root: '/',
  scrollBarActive: false,
  scrollBarHeight: 0,
  splitButtonEnabled: false,
  uri: '',
  uriLeft: '',
  uriRight: '',
  viewMode: 1,
  width: 100,
  workspacePath: '',
  x: 0,
  y: 0,
})
