import type { DiffViewState as DiffViewState } from '../DiffViewState/DiffViewState.ts'

export const createDefaultState = (): DiffViewState => ({
  assetDir: '',
  deltaY: 0,
  finalDeltaY: 0,
  focus: 0,
  gitRoot: '',
  handleOffset: 0,
  headerHeight: 40,
  height: 100,
  id: 1,
  initial: false,
  inputBoxHeight: 30,
  inputBoxMaxHeight: 214,
  inputFontFamily: '',
  inputFontSize: 15,
  inputFontWeight: 400,
  inputLetterSpacing: 0.5,
  inputLineHeight: 14.95,
  inputPadding: 2,
  inputPlaceholder: '',
  inputSource: 0,
  inputValue: '',
  isVisible: true,
  itemHeight: 20,
  maxInputLines: 5,
  maxLineY: 0,
  minimumSliderSize: 30,
  minLineY: 0,
  platform: 0,
  providerId: '',
  root: '/',
  scrollBarActive: false,
  scrollBarHeight: 0,
  splitButtonEnabled: false,
  viewMode: 1,
  width: 100,
  workspacePath: '',
  x: 0,
  y: 0,
})
