export const DiffEditorInput = 'DiffEditorInput'
export const SourceControlInput = 'SourceControlInput'
export const ViewAsTree = 'ViewAsTree'
export const CommitAndPush = 'CommitAndPush'
export const Refresh = 'Refresh'
